-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 15:32:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gimnasio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gimnasio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gimnasio` DEFAULT CHARACTER SET utf8 ;
USE `Gimnasio` ;

-- -----------------------------------------------------
-- Table `Gimnasio`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`Roles` (
  `Rol_ID` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Rol_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gimnasio`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`Persona` (
  `Persona_ID` CHAR(6) NOT NULL,
  `Tipo_Documento` VARCHAR(20) NOT NULL,
  `Numero_Documento` INT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Apellido_Paterno` VARCHAR(60) NOT NULL,
  `Apellido_Materno` VARCHAR(60) NULL,
  `Sexo` CHAR(1) NULL,
  `Direccion` VARCHAR(100) NULL,
  `NroCelular` VARCHAR(15) NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Correo` VARCHAR(100) NULL,
  `Telefono_Emergencia` VARCHAR(15) NULL,
  PRIMARY KEY (`Persona_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gimnasio`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`Turno` (
  `Turno_ID` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Fecha_Inicio` DATE NOT NULL,
  `Fecha_Fin` DATE NOT NULL,
  PRIMARY KEY (`Turno_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gimnasio`.`RolesPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`RolesPersona` (
  `Rol_ID` INT NOT NULL,
  `Persona_ID` CHAR(6) NOT NULL,
  `Fecha_Inscripcion` DATE NULL,
  `Fecha_Inicio_Contrato` DATE NULL,
  `Fecha_Fin_Contrato` DATE NULL,
  `Correo_Institucional` VARCHAR(100) NULL,
  `Numero_Seguro` VARCHAR(15) NULL,
  `Turno_ID` INT NULL,
  INDEX `FK_RP_Rol_idx` (`Rol_ID` ASC) ,
  INDEX `FK_RP_Persona_idx` (`Persona_ID` ASC) ,
  INDEX `FK_RP_Turno_idx` (`Turno_ID` ASC) ,
  PRIMARY KEY (`Rol_ID`, `Persona_ID`),
  CONSTRAINT `FK_RP_Rol`
    FOREIGN KEY (`Rol_ID`)
    REFERENCES `Gimnasio`.`Roles` (`Rol_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RP_Persona`
    FOREIGN KEY (`Persona_ID`)
    REFERENCES `Gimnasio`.`Persona` (`Persona_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RP_Turno`
    FOREIGN KEY (`Turno_ID`)
    REFERENCES `Gimnasio`.`Turno` (`Turno_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gimnasio`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`Local` (
  `Local_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Num_pisos` INT NOT NULL,
  PRIMARY KEY (`Local_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gimnasio`.`Maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`Maquinas` (
  `Maquinas_ID` INT NOT NULL,
  `Tipo` VARCHAR(15) NOT NULL,
  `Fecha_de_fabricacion` DATE NULL,
  `Estado_actual` VARCHAR(10) NULL,
  `Num_piso` INT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Local_ID` INT NULL,
  PRIMARY KEY (`Maquinas_ID`),
  INDEX `FK_Maquinas_Local_idx` (`Local_ID` ASC),
  CONSTRAINT `FK_Maquinas_Local`
    FOREIGN KEY (`Local_ID`)
    REFERENCES `Gimnasio`.`Local` (`Local_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gimnasio`.`Equip_digitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`Equip_digitales` (
  `Equipo_ID` INT NOT NULL,
  `Marca` VARCHAR(45) NULL,
  `Numero_de_serie` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Local_ID` INT NULL,
  PRIMARY KEY (`Equipo_ID`),
  INDEX `FK_ED_Local_idx` (`Local_ID` ASC) ,
  CONSTRAINT `FK_ED_Local`
    FOREIGN KEY (`Local_ID`)
    REFERENCES `Gimnasio`.`Local` (`Local_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gimnasio`.`Membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`Membresia` (
  `Membresia_ID` INT NOT NULL,
  `Rol_ID_Cliente` INT NULL,
  `Cliente_ID` CHAR(6) NULL,
  `Rol_ID_Entrenador` INT NOT NULL,
  `Entrenador_ID` CHAR(6) NOT NULL,
  `Rol_ID_Nutricionista` INT NOT NULL,
  `Nutricionista_ID` CHAR(6) NOT NULL,
  `Fecha_Inicio` DATE NULL,
  `Fecha_Fin` DATE NULL,
  CHECK (Rol_ID_Cliente = 2),
  CHECK (Rol_ID_Entrenador = 3),
  CHECK (Rol_ID_Nutricionista = 4),
  PRIMARY KEY (`Membresia_ID`),
  INDEX `FK_Membresia_RP_Rol_Invitado_idx` (`Rol_ID_Cliente` ASC, `Cliente_ID` ASC) ,
  INDEX `FK_Membresia_RP_Rol_Entrenador_idx` (`Rol_ID_Entrenador` ASC, `Entrenador_ID` ASC) ,
  INDEX `FK_Membresia_RP_Rol_Nutricionista_idx` (`Rol_ID_Nutricionista` ASC, `Nutricionista_ID` ASC) ,
  CONSTRAINT `FK_Membresia_RP_Rol_Cliente`
    FOREIGN KEY (`Rol_ID_Cliente` , `Cliente_ID`)
    REFERENCES `Gimnasio`.`RolesPersona` (`Rol_ID` , `Persona_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Membresia_RP_Rol_Entrenador`
    FOREIGN KEY (`Rol_ID_Entrenador` , `Entrenador_ID`)
    REFERENCES `Gimnasio`.`RolesPersona` (`Rol_ID` , `Persona_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Membresia_RP_Rol_Nutricionista`
    FOREIGN KEY (`Rol_ID_Nutricionista` , `Nutricionista_ID`)
    REFERENCES `Gimnasio`.`RolesPersona` (`Rol_ID` , `Persona_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gimnasio`.`Rutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`Rutina` (
  `Rutina_ID` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Rutina_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gimnasio`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gimnasio`.`Asistencia` (
  `Asistencia_ID` INT NOT NULL AUTO_INCREMENT,
  `Local_ID` INT NOT NULL,
  `Fecha_Asistencia` DATE NULL,
  `Hora_Entrada` TIME NULL,
  `Hora_Salida` TIME NULL,
  `Peso` DOUBLE NULL,
  `Rutina_ID` INT NULL,
  `Membresia_ID` INT NULL,
  `Rol_ID_Cliente` INT NULL,
  `Cliente_ID` CHAR(6) NULL,
  PRIMARY KEY (`Asistencia_ID`),
  INDEX `FK_Asistencia_Local_idx` (`Local_ID` ASC) ,
  INDEX `FK_Asistencia_Rutina_idx` (`Rutina_ID` ASC) ,
  INDEX `FK_Asistencia_Membresia_idx` (`Membresia_ID` ASC) ,
  INDEX `FK_Asistencia_Cliente_idx` (`Rol_ID_Cliente` ASC, `Cliente_ID` ASC) ,
  CONSTRAINT `FK_Asistencia_Local`
    FOREIGN KEY (`Local_ID`)
    REFERENCES `Gimnasio`.`Local` (`Local_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Asistencia_Rutina`
    FOREIGN KEY (`Rutina_ID`)
    REFERENCES `Gimnasio`.`Rutina` (`Rutina_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Asistencia_Membresia`
    FOREIGN KEY (`Membresia_ID`)
    REFERENCES `Gimnasio`.`Membresia` (`Membresia_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Asistencia_Cliente`
    FOREIGN KEY (`Rol_ID_Cliente` , `Cliente_ID`)
    REFERENCES `Gimnasio`.`Membresia` (`Rol_ID_Cliente` , `Cliente_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

